### ISSUE TITLE
POSTing feedback

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#213]
The only required parameters for POSTing feedback should be the connection's URI and a property that should change.

_This issue will be expanded soon_

**Comment by StanCallewaert** [comment]
This issue was inherited from https://github.com/iRail/iRail/issues/181.

## POST (https://api.irail.be/feedback/occupancy):

A JSON example of how a post request should look like is shown below:
```
{
  "connection": "http://irail.be/connections/8871308/20160722/IC4516",
  "vehicle":"http://api.irail.be/vehicle/?id=BE.NMBS.IC4516",
  "from":"http://irail.be/stations/NMBS/008871308",
  "to":"http://irail.be/stations/NMBS/008872009",
  "occupancy":"http://api.irail.be/terms/medium",
  "departureTime":"20160722T1642"
}
```

The departureTime is the datetime when the train leaves the **from station** in an ISO 8601 format.

Occupancy must be one of the following values: "https://api.irail.be/terms/low", "https://api.irail.be/terms/medium", "https://api.irail.be/terms/high".

**Comment by pietercolpaert** [comment]
Closing this issue as it will be fixed but cannot be closed by a specific commit

**Comment by ChristopheVersieux** [comment]
Is there any documentation available in order to know which parameters are mandatory?

The user could potentially send feedback from Connection // Vehicle // Liveboard screen, meaning that some of the information might or not be there.
