### ISSUE TITLE
Search stations by GPS

### ISSUE THREAD

**Issue by smurfy** [iRail/iRail#258]
Hi, either i missed it in the documentation or it's not "yet" possible to query for stations based on a gps position.

I really like such a feature :) 

i want to use iRail in my [fahrplan](http://www.github.com/smurfy/fahrplan) project, which supports (if the backend supports it) query by location.

**Comment by pietercolpaert** [comment]
Hi @smurfy and thanks for your suggestion! If you want you may pull request this in the API, however I don't really see the need for such a feature as there are only a bit more then 600 stations to query, which is maybe more cache-efficient to filter this on the client-side (or your application's server-side).

**Comment by pietercolpaert** [comment]
I just checked your app and it appears to have no server-side. Still I would advocate for each application to do the geo filter, unless you strongly disagree ;)

**Comment by smurfy** [comment]
Thanks for your input. I think i could implement the whole station query stuff including geo filtering client-side, but how often do the stations change? Is there some kind of best practice how ofter to update the stations list cache?

The Providers/Backends are abstracted in my app and i rather don't want to add some kind of "clear cache" button or something like that which only applies to one provider.

Otherwise i think implementing something like this to the API would be quite easy using the mongoDB $near filter.

**Comment by pietercolpaert** [comment]
## How it should be done "the nice way"

I think basic HTTP caching support would be the best solution although I have no experience implementing something like that in a custom C++ application. I have found one answer though on stackoverflow giving some kind of an answer of what you'd need: http://stackoverflow.com/questions/15965888/c-networking-library-supporting-response-caching

This would allow you to, every time you want to do something with the list of stations, you just send an HTTP request. Your HTTP library/implementation will then check whether it's time to refresh what you already have in memory or whether you can still use the previous response without sending anything to our server, without you having to implement a "clear cache" button for the end-user (which I strongly agree would not make any sense).

Now another problem appeared: apparently our cache headers got lost somewhere in the process of adding a server-side cache. We should re-implement those so that HTTP requests can be cached properly on the client-side as well.

## But let's be pragmatic

Maybe we should just implement your feature request as it will be common across more apps.

If any volunteer is up for that, feel free to alter the code over here: https://github.com/iRail/iRail/blob/master/api/data/NMBS/stations.php#L20 - The object returned from that function needs to be filtered/sorted on the basis of the [haversine formula](https://en.wikipedia.org/wiki/Haversine_formula). It also means adding a longitude and latitude request parameter over here: https://github.com/iRail/iRail/blob/master/api/requests/StationsRequest.php

**Comment by Bertware** [comment]
The stations list now has caching HTTP headers. An Etag and max-age header are sent with every response. The max-age header is set to 15 seconds (for now), as it's global for all endpoints. The etag header should be a good way to check if the list has been updated without having to transfer it all the time. I suggest you check once every 24 hours (or every 6 hours if you really want to be up to date all the time), but in reality the station list barely changes, on average maybe once in three months, or even less.

Sending user location data to a server is a potential privacy risk. Logs are stored and public as open data, and exact coordinates would reveal at least where people live when they're searching from home. A faster, privacy-respecting way is available, so this won't be implemented or hosted at irail.be.

Advantages of using the stations list
- Less traffic/data (no HTTP request for every lookup)
- Faster computations (Our server isn't a supercomputer, every php script takes time)
- Cached data: this goes along with the less traffic, but all requests for the station list are cached, while any request for a specific location would have to be calculated. It'd always be a cache miss.
- Lookup in multiple databases: You can look for the x nearest stations over multiple datasets at once if you want, which is really interesting, for example in border regions. A request to multiple servers would be slower and return too much information: if you want the 5 closest stations, you would have to query every server/provider for the 5 closest stations (every train operator, bus operator, ...).
- Respects privacy: no user coordinates are transferred over the internet. The location of a user stays private and is only known on the users device.

My suggested solution would be to store both the stations file and the last etag on the user device, then use this etag whenever checking for an updated list. This takes only 20ms in case there's no change. Then calculate the closest stations in-app, which is a lightweight task with todays smartphones (To give you an idea: my 5 year old smartphone does this local lookup in a few milliseconds).
