### ISSUE TITLE
Enable caching headers

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#259]
In every request, we should enable caching headers with both etag headers, telling the client which version is exposed at a certain moment (e.g., for the stations list this is very interesting) and how long the response may be used (cache control max-age) header.

The issue was discovered in this discussion: https://github.com/iRail/iRail/issues/258#issuecomment-242967933

**Comment by pieterbeulque** [comment]
What seems like an appropriate max-age time? One week or possibly even one year?

**Comment by pietercolpaert** [comment]
For stations: 1 day I would say. The stations can be updated manually
through the https://github.com/iRail/stations repo. As you can see, changes
actually happen quite often. Maybe we can also implement an e-tag somehow?

For all other resources that get scraped from SNCB I would say 1 minute for
now. In the future I would only implement an e-tag though, as the occupancy
level can change at any random moment.

Op zo 28 aug. 2016 12:53 schreef Pieter Beulque <notifications@github.com>:

**Comment by pieterbeulque** [comment]
I always implement E-Tags by setting a quick `md5(serialize($fooResponse))` as E-Tag. That could work here too.

E-Tags without Expires or Cache-Control: max-age won't do anything. Source: https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers#cache-control

> Without the cache-control header set, no other caching headers will yield any results.

**Comment by pietercolpaert** [comment]
Makes sense!

Op zo 28 aug. 2016 13:37 schreef Pieter Beulque <notifications@github.com>:

**Comment by pieterbeulque** [comment]
I'd still pass a max-age in the Cache-Control header though.

Also, are you sure If-None-Match request headers and 304 Not Modified response headers are handled correctly?

**Comment by pietercolpaert** [comment]
@pieterbeulque The problem right now is that for responses incorporating how busy a train is, we never know when a train could be marked as “busy” by a POST request... Hence why we removed the max-age header

**Comment by pietercolpaert** [comment]
@Bertware Canyou check on Monday whether we handle if-none-match correctly? Good comment by Pieter https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match

**Comment by Bertware** [comment]
@pietercolpaert semi-related but when I start working on the LinkedConnections > iRail API I'm pretty sure I'm going to make occupancy a separate endpoint for caching, performance, and scalability reasons.

 I expected nginx to take care of the if-none-match, will check on monday, good point!

**Comment by Bertware** [comment]
I implemented a 304 response when if-none-match matches the current ETag. 
This provides bandwidth savings, though clients still experience the same response time as we have to compile the entire answer.

@pieterbeulque You suggested to still include a max-age header, but wouldn't setting a max-age be a possible cause for outdated data?
If we send a max-age header for 15 seconds, and one second later NMBS data changes, you're using outdated data for 14 seconds. It's only a matter of timing at this point, as there is barely any data usage due to the if-none-match, no?

**Comment by pieterbeulque** [comment]
Of course, but you'll always risk outdated data when you want to implement caching… That's not the point.

If you always want to fetch or revalidate from the server, you set `Cache-Control: no-cache` and be done with it. If you want to improve caching, you'll lose some data accuracy.

We'll need to figure out a decent caching policy and communicate this well.

Live data for train departures could for example be cached for 30 seconds. That's a perfect compromise for better app responses, to me.

A list of railway stations could be cached for 7 days or more, as it's unlikely a new one gets built in a week 😄 

It's all about the trade-offs.

> If we send a max-age header for 15 seconds, and one second later NMBS data changes, you're using outdated data for 14 seconds

True, but that's exactly the point of caching.

> It's only a matter of timing at this point, as there is barely any data usage due to the if-none-match, no?

Yeah, but as you said, response timings are the same because you're still building the whole response. So you don't gain anything (except download times) from this caching, and could just as well just use `Cache-Control: no-cache`.

**Comment by Bertware** [comment]
Caching is now implemented both server side and in HTTP headers, mostly by ETag which gives the best data-savings in this case, along with time saving in some cases.
