### ISSUE TITLE
Different results when searching for a connection

### ISSUE THREAD

**Issue by svaningelgem** [iRail/iRail#280]
In attach you'll see 2 screenshots (taken at about the same time through the BeTrains app which uses the iRail framework).

What happened:
I searched for a train from BXL to Herent, and got a list (fine). But as you can see there is one at 16.14 with no delay if I search for a connection to Herent, but that exact same train has a delay of 4 minutes when I search for a connection to Leuven.

![screenshot_2017-04-12-16-42-31](https://cloud.githubusercontent.com/assets/199434/24997133/dbe046fa-2035-11e7-8082-c77f9f09e2cf.png)
![screenshot_2017-04-12-16-42-40](https://cloud.githubusercontent.com/assets/199434/24997134/dbf67c22-2035-11e7-9b30-f345eba42741.png)

**Comment by Bertware** [comment]
Please do the same searches at the NMBS site (where the iRail api gets its data at this moment). There are likely differences between different pages on the NMBS site. This might be due to caching or the database at their side. Can you reproduce/verify with the nmbs route planner (online) when you notice this again?
