### ISSUE TITLE
Connection from.. to.. results in strange results

### ISSUE THREAD

**Issue by lvthillo** [iRail/iRail#342]
I try to use the API to find a connection between Essen (Belgium) to Kapellen.
https://api.irail.be/connections/?from=Essen&to=Kapellen?&format=json

The json gives me results for "Brussels-Chapelle/Brussels-Kapellekerk".
When I try from Kapellen to Essen
 https://api.irail.be/connections/?from=Kapellen&to=Essen?&format=json the json provides me a connection to Kessel.

Maybe the arrival result contains some wrong regex?
I'm also arriving in a different train but that's probably because there are 'via's' calculated to bring me from Essen to "Brussels-Chapelle/Brussels-Kapellekerk"

Checking the liveboard provides good results: https://api.irail.be/liveboard/?station=essen/&format=json while I would think the same function is used to retrieve the station.

As workaround/implementation I can translate every station's name to its ID when I check if the station exist, but a fix will be appropriate

**Comment by Bertware** [comment]
@pietercolpaert do you know the reason for this line of code?
https://github.com/iRail/iRail/blob/master/api/data/NMBS/connections.php#L29
Seems to be the only difference between the from and to field.

**Comment by pietercolpaert** [comment]
I have no idea anymore. Would it fix the issue?

**Comment by Bertware** [comment]
@lvthillo Regarding the kessel issue: 
There are multiple invalid URL's in your issue. I also overlooked them first, but they're causing issues:

> /connections/?from=Essen&to=Kapellen?&format=json
> /connections/?from=Kapellen&to=Essen?&format=json

There is a question mark after the station name, which is included in your query.

> /liveboard/?station=essen/&format=json

There is a forward slash after the station name, which is included in your query. Somehow this doesn't affect the lookup while the question mark does, but they shouldn't be there anyway. The issue is resolved when using proper URLs

**Comment by pietercolpaert** [comment]
Aha! The question mark gets interpreted as a regular expression, which makes the n optional, so the algorithm determines Kappellekerk to be the most relevant match.

The solution here should indeed be not to:
 1. Remove the `?`
 2. Always use the identifiers of the stops instead of the full name (prone to errors)
