### ISSUE TITLE
Remark "tag" from irail.be

### ISSUE THREAD

**Issue by amin89** [iRail/iRail#391]
Is it possible to know from where "code : SNCB_2090_HINT "  and relied description are retrieved ?
I don't found them through this real-time SNCB feed 
https://sncb-opendata.hafas.de/gtfs/static/c21ac6758dd25af84cca5b707f3cb3de%20
 
```
"remarks": {
        "number": "2",
        "remark": [
          {
            "id": "0",
            "code": "SNCB_2090_HINT",
            "description": "The original, planned timetable of this trip has been replaced by a new one due to a redirection. Based upon the new timetable, the connection cannot be guaranteed. Consult the overview for an alternative trip."
          },
          {
            "id": "1",
            "code": "SNCB_2090_HINT",
            "description": "The original, planned timetable of this trip has been replaced by a new one due to a redirection. Based upon the new timetable, the connection cannot be guaranteed. Consult the overview for an alternative trip."
          }
        ]
      },
```

Thank you for any help !

**Comment by Bertware** [comment]
Our data comes from a mix of internal APIs (for example, where the official NMBS website and app get their data) and scraping (meaning we load the official website and retrieve the right data from the HTML code). Without knowing where this snippet comes from it's hard to point to the exact source, but I'd guess this comes from an internal mobile API. No idea what the SNCB_2090_HINT really means, but we include these field since they sometimes contains useable data (specifically when it comes to delays, cancellations, maintenance works, ...).

You're linking to a static GTFS file, a file that contains the planned timetables. The accompanying GTFS-RT feed with realtime updates should contain the same data, as both come from the same publisher (HAFAS), but the snippet you showed is traveler-friendly, while the GTFS-RT data will only indicate if a (part of a) trip has been replaced. You can probably create a similar response based on the GTFS & GTFS-RT data. 

Hope this helps you with your question, feel free to ask if you have more questions.
