### ISSUE TITLE
No results for stations with a slash in their name

### ISSUE THREAD

**Issue by cimm** [iRail/iRail#40]
Finding connections by station ID between, say, `Aalst` to `Aalter` works perfect

    http://api.irail.be/connections/?to=BE.NMBS.008895000&from=BE.NMBS.008891140 [WORKS]

but `Aalst` to `Brussel-Centraal/Bruxelles-Central`

    http://api.irail.be/connections/?to=BE.NMBS.008895000&from=BE.NMBS.008813003 [BROKEN]

returns "No station found for Brussel-Centraal/Bruxelles-Central" result in plain text. This happens for all stations with a slash in their name. Tried both the JSON and XML endpoints but they both have the same problem, specifying the language in the query doesn't help ether.

I can work around the bug when I replace the station ID with the string `Brussel-Centraal` but isn't that problem exactly why you would use an ID in the first place?

    http://api.irail.be/connections/?to=BE.NMBS.008895000&from=Brussel-Centraal [WORKS]

**Comment by pietercolpaert** [comment]
Hi @cimm,

Indeed! 

http://api.irail.be/connections/?to=BE.NMBS.008895000&from=BE.NMBS.008813003 

is broken at the moment. If you add however

http://api.irail.be/connections/?to=BE.NMBS.008895000&from=BE.NMBS.008813003&lang=nl
or
http://api.irail.be/connections/?to=BE.NMBS.008895000&from=BE.NMBS.008813003&lang=fr

it does work.

The real problem is located over here: https://github.com/iRail/hyperRail/blob/master/app/controllers/StationController.php#L61. That's the webservice code that is used everywhere in the iRail project to resolve a name to an ID. A quick fix would be to split the q at a / and only use the first part. Added it as an issue to hyperRail

**Comment by cimm** [comment]
Great, thanks Pieter. I tried the EN version and not the NL or FR ones which would have worked. :crying_cat_face:
