### ISSUE TITLE
Approching/at the platform

### ISSUE THREAD

**Issue by quentinguidee** [iRail/iRail#402]
Hello!

I don't know if it's a missing feature or a data that I don't find, but is there a way to retrieve the data "train approaching/train at the platform" from the liveboard ?

Or SNCB/NMBS does this with `time`and `delay` manually ?

Thank you!

**Comment by Bertware** [comment]
We are currently limited to the data available on the website, app and the nmbs "trainmap" website. The screens seem to have their own (internal) datasource which might get more data from the trains or rail network. Since this data isn't available in the other channels, we can't include it in the API responses. As soon as we know where to get it we'll provide it through iRail. 

The data we do have is arrived/left, but this data doesn't seem to have the same precision as the arriving/at the platform data.

**Comment by quentinguidee** [comment]
Oh :/ thanks! Could you tell me, if you know it, the scale of imprecision? 10s/20s/more?

**Comment by Bertware** [comment]
No idea, identical to the NMBS app anyway. (If the NMBS app is wrong, iRail is wrong as well)

**Comment by quentinguidee** [comment]
Ok I'll try! Thank you very much for this API and for your help! :)
