### ISSUE TITLE
Error code CGI_NO_SERVER - Impacted apps: irail.be, HyperRail, BeTrains

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#445]
Hello,

After having issues with my app thi smorning, I also tried HyperRail and irail, and it seems that they are all impacted.

How to reproduce:
https://api.irail.be/connections.php?to=Tournai&from=Mons&date=120921&time=1250&timeSel=depart&lang=en&typeOfTransport=train&format=json&fast=true&alerts=true

Result:
{
error: 500,
message: "Could not get data: This request failed. Please check your query. Error code CGI_NO_SERVER. Please report this issue at https://github.com/irail/irail/issues/new"
}

Vehicle API is also broken as all vehicles report a 404 not found message.

Related to NMBS server maybe?

**Comment by Bertware** [comment]
Do you happen to have the original nmbs app on your device? (Not the new one). Looks like they shut down the servers for the old app, which were also used by irail. Will verify and look for a new data source if needed.

**Comment by ChristopheVersieux** [comment]
Unfortunately, I don't have it anymore.

**Comment by Bertware** [comment]
Liveboards and vehicles are working now, so seems like the nmbs server is just having some issues. You might also get error code fail, but seems like they're getting it back up and running. We should start thinking about a backup data source though, since they seem to be pushing more and more towards their new app (which is significantly harder to reverse-engineer)

**Comment by Bertware** [comment]
Should be fixed now, altered the strings we use to search for stations (unclear how that affects the actual search, all of a sudden these extra fields were making the queries slow)
