### ISSUE TITLE
Docker support for PHP8.

### ISSUE THREAD

**Issue by Tjoosten** [iRail/iRail#446]
Hey, 

First of all thank you for the great API. You've made. But im wondering if you can support php 8.0 or 8.1. in the docker container(s). Because i have some ideas for cleaning up the php code. But restricted by the php7 limitation. 

King Regards, 
Tim Joosten

**Comment by Bertware** [comment]
We bumped the minimum required version to PHP 7.4 and updated our server to 8.0. I updated the docker file as well, could you verify it works?

You're free to improve on the code, but keep in mind that since it's a scraper, everything can change quickly, and right now we're keeping backwards compatibility (which also means keeping a lot of old code, moving to the default json_encode for example would require a rather complicated adapter). Datasource classes tend to be quickly rewritten from scratch when changes to underlying APIs or webpages happen, which explains the less-than-ideal code there, along with having to keep backwards compatibility.
