### ISSUE TITLE
Live departures: Bruxelles-Midi ID 008747100 not recognized

### ISSUE THREAD

**Issue by jeanbaptistemarie** [iRail/iRail#476]
Hello there,

The live departure endpoint return an error for Bruxelles-Midi station ID
`{"error":404,"message":"Could not find a station with id 008747100."}`

[https://api.irail.be/liveboard/?id=BE.NMBS.008814001&arrdep=departure&lang=fr&format=json&alerts=true](https://api.irail.be/liveboard/?id=BE.NMBS.008814001&arrdep=departure&lang=fr&format=json&alerts=true)

What's weird is that the arrivals service do return results for the same ID
[https://api.irail.be/liveboard/?id=BE.NMBS.008814001&arrdep=arrival&lang=fr&format=json&alerts=true](https://api.irail.be/liveboard/?id=BE.NMBS.008814001&arrdep=arrival&lang=fr&format=json&alerts=true)

Is this something that can be fixed?
Thanks

**Comment by Bertware** [comment]
The id which cannot be found, 008747100, is the id of one of the stations in the response. 

Looked it up and it corresponds to Rennes (UIC 8747100, lat ;48.103517 lon -1.672744). I'll add it in the stations data which should resolve the issue.

**Comment by jeanbaptistemarie** [comment]
Thank you.
Isn't it an issue that the endpoint does not return anything if a single station UIC code does not exist in the stations index?

Could we make it returns the time board entries even if a UIC code is missing?

**Comment by Bertware** [comment]
Fixed in https://github.com/iRail/stations/commit/5f3058d7a2419b74a48127d6ba6ea77a4f24b8f4



> Thank you. Isn't it an issue that the endpoint does not return anything if a single station UIC code does not exist in the stations index?
> 
> Could we make it returns the time board entries even if a UIC code is missing?

In order to return a correctly formatted response, the data from irail/stations (or another additional data source) is needed. While skipping these stations completely could be a solution, it introduces a new problem: The list may or may not be complete. Skipping this entry in the list would have meant that this issue would not have been discovered, leading to incomplete responses for a prolonged period of time. 

It's definitely something which should be fixed sometime in the future, but rather by a fallback datasource and error reporting than by silently skipping results.
