### ISSUE TITLE
Error in Connections API calls

### ISSUE THREAD

**Issue by Bryn72** [iRail/iRail#508]
I seem to notice that the iRail api Connections doen't care about the results parameter that is passed in the query. It returns all available trainroutes, regardless of the amount specified in the results querystring.

**Comment by Bertware** [comment]
This function probably stopped working while we moved between different internal data sources, and has some advantages. It means we can cache more data since requests can't differ on the number of requested results. This also reduces the load we put on the NMBS.

It would be possible to restore this functionality, by fetching all trainroutes then filtering before they are returned in the response. This would mean a response with fewer results is not faster, but it would be smaller.

What would be the use-case for you?

Somewhat relates to #504 .

**Comment by Bertware** [comment]
Closed due to inactivity. Reopen if this is still an issue.
