### ISSUE TITLE
Some disturbances have the wrong type

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#524]
https://api.irail.be/v1/disturbances/?lang=nl

The item with `id="4"` should be `type="planned"`.
<img width="978" alt="Screenshot 2024-05-14 at 19 25 31" src="https://github.com/iRail/iRail/assets/995815/b3dcc460-2e75-4a14-8368-1844dbdbe32a">

I suspect something going wrong here: https://github.com/iRail/iRail/blob/701ef3985f1a39eb45bf1f0c54b7988fbca62062/app/Repositories/Nmbs/NmbsRssDisturbancesRepository.php#L141

**Comment by Bertware** [comment]
This is the same disturbance which caused the entire endpoint to go down earlier, and looking at it now it doesn't only lack an id, but it also lacks a link to more information. That link is used to determine the disturbance type, as you correctly linked in the issue. 
This seems to be a bug or user error in the NMBS systems, and since all other issues (even newer issues) still are in the same format, I'd prefer to let this one pass and only fix it if it ever occurs again. This way the code doesn't get too cluttered with needless fixes for malformed upstream data.

Correct example
```
<item>
<title><![CDATA[La Louvière-Zuid - Charleroi-Centraal]]></title>
<description><![CDATA[Tijdens het weekend van 8-9/06 werkt Infrabel aan het spoor.<br><br>De vertrektijden van sommige S62-treinen La Louvière-Centrum - Morlanwelz - Charleroi-Centraal wijzigen.<br><br>De reisplanner houdt al rekening met deze aanpassingen.]]></description>
<link>http://www.belgianrail.be/jp/nmbs-realtime/help.exe/nl?tpl=showmap_external&amp;tplParamHimMsgInfoGroup=works&amp;messageID=84148&amp;channelFilter=rss_line_90&amp;</link>
<pubDate>Tue, 14 May 2024 10:27:57 +0200</pubDate>
<guid isPermaLink="false">http://www.belgianrail.be/jp/sncb-nmbs-routeplanner/help.exe/nn?tpl=him_map84148</guid>
<dc:creator></dc:creator>
</item>
```

This, incorrect example:
```
<item>
<title><![CDATA[Verviers-Centraal - Spa-Géronstère]]></title>
<description><![CDATA[Van 9 tot en met 12/05 en 18 tot en met 20/05 werkt Infrabel aan het spoor.<br><br>Een NMBS-bus vervangt alle treinen tussen Verviers-Centraal en Spa-Géronstère.<br><br>De reisplanner houdt al rekening met deze aanpassingen.<br/><a href="[https://www.belgiantrain.be/nl/support/faq/faq-routes-schedules/faq-bus#faq](view-source:https://www.belgiantrain.be/nl/support/faq/faq-routes-schedules/faq-bus#faq)">(NL) Meer info over de NMBS-bussen (FAQ)</a><br/><a href="[https://www.belgianrail.be/jp/download/brail_him/1715672782719_NL_2405004_S.pdf](view-source:https://www.belgianrail.be/jp/download/brail_him/1715672782719_NL_2405004_S.pdf)">Waar is mijn bushalte?</a><br/>]]></description>
<link></link>
<pubDate>Tue, 14 May 2024 09:46:23 +0200</pubDate>
<guid isPermaLink="false">http://www.belgianrail.be/jp/sncb-nmbs-routeplanner/help.exe/nn?tpl=him_map83118</guid>
<dc:creator></dc:creator>
</item>
```

Reopen if it happens again on another message, in that case some regex should be added as a fallback.

**Comment by jncn** [comment]
Thanks for the clarification!
