### ISSUE TITLE
504 errors at beginning of day

### ISSUE THREAD

**Issue by LaurentVB** [iRail/iRail#534]
Hello there
Yesterday morning and this morning, my app is experiencing 504 errors when querying the `https://api.irail.be/v1/vehicle` endpoint, between approx 6h and 8h. Things seem to fix after 8.
Is this a known issue?
Cheers

**Comment by LaurentVB** [comment]
I was hoping to jump into the logs for yesterday, but [it seems like the uploads have stopped](https://gtfs.irail.be/logs/)

**Comment by Bertware** [comment]
This could be caused by the GTFS refresh, which happens around 7 (GTFS background cache refresh of large objects) and finishes around 8 (spread cache expiration of detailed, small cache entries). Alternatively it could be related to #533 

Another, likely reason would be some form of rate-limiting happening in the underlying internal APIs, something which I'd need to see happening to be able to diagnose exact API requests/responses happening in the backend. Currently only iRail HTTP 500 responses are stored in detail, including backend requests, since other error codes often are outside of iRails control and would be too much to store.

Regarding the query logs, those are logged to a database table, and then flushed to gtfs.irail.be in a nightly job. The nightly python job is currently not running due to some form of timeout or out-of-memory exception, but logs are still being collected and will become available later on when they get published in a batch. These are however query/response logs for analyzing route suggestions etc, not to be confused with debug logging from the iRail application itself.

**Comment by LaurentVB** [comment]
Closing this, haven't experienced it in the last weeks.
