### ISSUE TITLE
Liveboard returns empty array for all stations

### ISSUE THREAD

**Issue by VandeVoordeMatthias** [iRail/iRail#541]
I'm having a problem with the liveboard endpoint. For example, when making a request to
https://api.irail.be/v2/liveboard/departure/Gent-Sint-Pieters,
the API consistently returns an empty array.

This behaviour occurs for all stations I've tested. However, when checking the NMBS website for departures, the expected data is displayed correctly.

**Comment by Bertware** [comment]
Thanks for reporting this!  Since the response code is still 200, monitoring didn't trigger.

There were issues with incorrect GTFS data earlier, which were quickfixed by restoring a previous GTFS dataset on gtfs.irail.be, but I never had time to investigate the actual problem. I figured the NMBS would send a correct dataset the next day.

It appears however that the NMBS has completely removed train traffic from 2024 from their GTFS file. If we didn't have an archive of GTFS files, we would have no idea which train are running between which stations in the next two weeks. Usually this data is just combined, since separating them just causes issues. As far as I can see NMBS did this in the old GTFS data up to november 28th, meaning that it should not be an issue to keep using that dataset for two weeks until the 2024 timetable is no longer needed.

**Comment by Bertware** [comment]
Fixed since a week ago, as the GTFS file is correct again
