### ISSUE TITLE
Looking for an efficient way to retrieve data from iRail API

### ISSUE THREAD

**Issue by amcaw** [iRail/iRail#547]
Hello everyone,

I apologize for posting this in the Issues section, as it's not a bug report. Feel free to tell me to RTFM. I'm seeking help with using the iRail API to collect detailed train journey data.

Objective: I aim to use Python to gather all train journeys for a full day, including:

- Every stop on each trip
- Delays at each stop
- Information on cancelled trains

The desired output is a CSV file with the following columns:

Train_number;Station_name;Station_position (first, last, intermediate);scheduled_arrival;actual_arrival;arrival_delay;scheduled_departure;actual_departure;departure_delay;is_cancelled

I've attempted to write a Python script that checks each train of the day individually. However, this method is extremely slow and inefficient.

I came across the [Linked Connections feature](https://hello.irail.be/) for retrieving delays, but I'm unsure if it's still supported and I didn't understand how to use it.

Anyway I'm looking for best practices for efficiently using the iRail API with Python to collect the required data. Any sample code or resources that could guide me in optimizing my script while ensuring I don't hit the API unnecessarily would be really helpful.

Thank you in advance for your assistance!

**Comment by Bertware** [comment]
Some quick initial notes:

- please don't scrape the irail api, ideally all calls to the irail api are caused by some user interaction (making a search in an app, voice assistant, ... ) or user configuration (a display showing departures from a station, a widget showing a favourite connection, ...). Scraping the iRail api risks overloading both the API and the services behind it. The iRail api has rate limiting in place to prevent this, which means scraping won't work reliably.

- linked connections would be a perfect source for this. It's based on the gtfs and gtfs realtime data, but already expanded in a list of all departures. It is designed for large loads, so there's no problem with fetching a large number of pages in a short interval.

- gtfs and gtfs realtime would work really well for your use case as well. The gtfs dataset (available for direct download from gtfs.irail.be, so you don't need to go through the hassle of signing contracts with the nmbs to get access) contains all trips for multiple months in a single zip file, with a database like structure. There are many tools for working with gtfs since it's a worldwide standard. We don't have the realtime files on gtfs.irail.be yet, though I should be able to fix this one of the coming days. The realtime data contains deviations such as delays and cancellations, and must be combined with the static data to get a result.

**Comment by amcaw** [comment]
Thank you for your response and explanation! I’ll proceed with the linked connection approach then. Could you guide me on how to get started? I’m unsure which GitHub repository I should use. Additionally, does linked connection provide the option to retrieve a complete dataset in JSON or CSV format at the end of the day?
