### ISSUE TITLE
English station can be abbreviation of Dutch / French

### ISSUE THREAD

**Issue by brechtvdv** [iRail/iRail#66]
The problem is a bit complicater because those abbreviations are not official names of stations.

Eg. Bru.-Noord / Brux.-Nord

**Comment by ChristopheVersieux** [comment]
If you pick the one you want (NL or FR) for Brussels and maybe as we discover a few others, it will still be better than everything in NL.

English people travelling in Belgium will never know that Zinnik is Soignies, Doornik is Tournai, or Bergen for Mons. Even Belgian users using the app are still wondering what happens when the name changes from one screen to another. That is a really big issue for the user experience.

My proposal would be to keep the NL (as currently) where there is a doubt, but the default EN one for the others and so, we can fix most of the issues.

**Comment by brechtvdv** [comment]
By doing an extra request (performance loss..), if there are abbreviated names, I can return proper English names

**Comment by pietercolpaert** [comment]
Can I close this?

**Comment by brechtvdv** [comment]
Yes. The fix-english branch in my fork contains a solution, but your resolver is much better and cleaner to fix this problem.

**Comment by pietercolpaert** [comment]
Oh... In that case! Could you pull request a test-case to https://github.com/iRail/stations/blob/master/tests/StationsTest.php#L61 where this particular case is tested?

Something like this:
```php
$result5 = Stations::getStations("Bru.-Noord / Brux.-Nord");
$this->assertEqual("http://irail.be/stations/NMBS/008812005",$result5->{"@graph"}[0]->{"@id"});
```

But then with better handling of when item `[0]` wouldn't be set ;-)

**Comment by pietercolpaert** [comment]
@brechtvdv as this is fixed, you'll be able to remove the 2 requests

**Comment by brechtvdv** [comment]
Nice! I'll rewrite it later!

**Comment by pietercolpaert** [comment]
Can you open an issue for it?
